// Shared server-rendered footer; also used to generate the static page footers.
const escape = value => String(value ?? "").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
export function renderFooter(settings, year = new Date().getFullYear()) {
  const s=Object.fromEntries(Object.entries(settings).map(([key,value])=>[key,escape(value)]));
  const icon=name=>'<i class="'+name+'" aria-hidden="true"></i>';
  return `<footer id="site-footer" class="site-footer" dir="rtl"><div class="site-footer-inner"><div class="site-footer-grid">
<section class="site-footer-company" aria-label="عن الشركة"><div class="site-footer-brand"><img src="/assets/logo.png" alt="" width="48" height="48" loading="lazy"><h3 data-company-name>${s.companyName}</h3></div><p>شريكك الموثوق في حلول المصاعد والسلالم المتحركة في المملكة</p><div class="site-footer-social">
<a href="https://www.instagram.com/elevationtech0" target="_blank" rel="noopener noreferrer" aria-label="إنستغرام">${icon("fab fa-instagram")}</a><a href="https://www.tiktok.com/@elevationtech0" target="_blank" rel="noopener noreferrer" aria-label="تيك توك">${icon("fab fa-tiktok")}</a><a href="https://www.snapchat.com/add/elevationtech0" target="_blank" rel="noopener noreferrer" aria-label="سناب شات">${icon("fab fa-snapchat-ghost")}</a><a href="mailto:${s.companyEmail}" aria-label="راسلنا بالبريد الإلكتروني">${icon("fas fa-envelope")}</a></div></section>
<section><h4>روابط سريعة</h4><ul><li><a href="/">الرئيسية</a></li><li><a href="/pages/about.html">من نحن</a></li><li><a href="/pages/services.html">خدماتنا</a></li><li><a href="/pages/products.html">منتجاتنا</a></li><li><a href="/pages/projects.html">مشاريعنا</a></li><li><a href="/blog/">المدونة</a></li></ul></section>
<section><h4>خدماتنا</h4><ul><li><a href="/pages/products.html">توريد المصاعد</a></li><li><a href="/pages/services.html">الصيانة الدورية</a></li><li><a href="/pages/services.html">التحديث والتطوير</a></li><li><a href="tel:${s.emergencyPhone}" data-emergency-phone>خدمة الطوارئ</a></li><li><a href="/pages/products.html">السلالم المتحركة</a></li></ul></section>
<section><h4>تواصل معنا</h4><ul class="site-footer-contact"><li>${icon("fas fa-map-marker-alt")}<span data-company-address>${s.companyAddress}</span></li><li>${icon("fas fa-phone")}<div><a href="tel:${s.companyPhone}" dir="ltr">${s.companyPhone}</a><a href="tel:${s.emergencyPhone}" data-emergency-phone dir="ltr">${s.emergencyPhone}</a></div></li><li>${icon("fas fa-envelope")}<a href="mailto:${s.companyEmail}">${s.companyEmail}</a></li><li>${icon("fas fa-clock")}<span>الأحد - الخميس: 8:00 - 17:00</span></li></ul></section>
</div><div class="site-footer-bottom"><p><span data-footer-text>${s.footerText}</span> · © <span id="year">${year}</span></p><div><a href="/blog/">المدونة</a><a href="/pages/contact.html">تواصل معنا</a><a href="/sitemap.xml">خريطة الموقع</a></div></div><div class="site-footer-credit" lang="en" dir="ltr">Powered by <span>Twins Technology</span></div></div></footer>`;
}

